### ISSUE TITLE
No such file or directory: 'configs/staking.yaml

### ISSUE THREAD

**Issue by dazzag24** [AramKoorn/TenBagger#12]
```
❯ tenbagger --portfolio my_portfolio
    ____             __  ____      ___
   / __ \____  _____/ /_/ __/___  / (_)___
  / /_/ / __ \/ ___/ __/ /_/ __ \/ / / __ \
 / ____/ /_/ / /  / /_/ __/ /_/ / / / /_/ /
/_/    \____/_/   \__/_/  \____/_/_/\____/


Traceback (most recent call last):
  File "/home/badger/.pyenv/versions/3.8.8/bin/tenbagger", line 33, in <module>
    sys.exit(load_entry_point('tenbagger==0.7.0', 'console_scripts', 'tenbagger')())
  File "/home/badger/.pyenv/versions/3.8.8/lib/python3.8/site-packages/tenbagger/cli.py", line 121, in main
    port = Portfolio(args.portfolio)
  File "/home/badger/.pyenv/versions/3.8.8/lib/python3.8/site-packages/tenbagger/src/portfolio/core.py", line 13, in __init__
    super().__init__()
  File "/home/badger/.pyenv/versions/3.8.8/lib/python3.8/site-packages/tenbagger/src/portfolio/crypto.py", line 8, in __init__
    self.apy = read_yaml('configs/staking.yaml')
  File "/home/badger/.pyenv/versions/3.8.8/lib/python3.8/site-packages/tenbagger/src/utils/utilities.py", line 153, in read_yaml
    with open(f'{loc}') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/staking.yaml'
```

**Comment by AramKoorn** [comment]
If you cd to the root of the library it should work. 

cd /path_to_where_you_cloned_TenBagger/TenBagger

**Comment by dazzag24** [comment]
OK that fixes it thanks.  Not sure how I ended up in the subdirectory.  Maybe the 

```
python3 setup.py install && pip3 install .
```
step changed the cwd from the root one?

**Comment by AramKoorn** [comment]
I don't think that changed directory. But I'm thinking to create a hidden folder in the root of the user to store the configurations. Then the user doesn't has to change the working directory in order to run the app.

**Comment by amarjandu** [comment]
@AramKoorn looking to contribute, is this a good first issue?

**Comment by AramKoorn** [comment]
@amarjandu Hey awesome that you want to help! This issue is already solved and will be closed. I created a new good first issue #13  which you can pick up if you want. I also need add unit tests and fix some current failing test for which I created this #8 issue.
